export enum OperationType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  TRANSFER = 'TRANSFER',
  TRANSFORM = 'TRANSFORM',
  SPLIT = 'SPLIT',
  GROUP = 'GROUP',
  UNGROUP = 'UNGROUP',
  INACTIVE = 'INACTIVE',
  CREATE_DOCUMENT = 'CREATE_DOCUMENT',
  DATA_SHEET = 'DATA_SHEET',
  PARTIALLY_CONSUME = 'PARTIALLY_CONSUME',
}